apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: second-argocd
spec:
  server:
    route:
      enabled: true
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: reencrypt
  sso:
    dex:
      openShiftOAuth: true
